version: '3.0'

services:
  speedtest:
    build:
      dockerfile: Dockerfile
    depends_on:
      - telegraf
    links:
      - telegraf
    restart: on-failure

  telegraf:
    image: telegraf:1.18
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '8125:8125/udp'
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: on-failure

  influxdb:
    image: influxdb:1.8
    env_file: influx/config.env
    ports:
      - '8086:8086'
    volumes:
      - ./influx/imports:/imports
      - ~/volumes/speedtest/influx/data:/var/lib/influxdb
    restart: on-failure

  grafana:
    image: grafana/grafana:8.0.2
    depends_on:
      - influxdb
    env_file: grafana/config.env
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - ~/volumes/speedtest/grafana/data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/etc/grafana/dashboards:ro
    restart: on-failure
