version: '3.0'

services:
  webmin:
    container_name: webmin
    image: eafxx/bind #arm64 support image
    ports:
      - "8084:8084/tcp"
    env_file: config.env
    volumes:
      - ~/volumes/webmin/data:/data
    restart: unless-stopped
