version: '3.0'

services:
  webmin:
    container_name: webmin
    image: eafxx/bind #arm64 support image
    ports:
      - "8084:10000/tcp"
    volumes:
#      - ~/volumes/webmin/data:/data
      - ./conf/etc/miniserv.conf:/data/webmin/etc/miniserv.conf
    restart: unless-stopped
